vfile add vhdl work src/TB/timer_tb.vhd
vfile add vhdl work src/TB/address_decoder/address_decoder_1.vhd
vfile add vhdl work src/TB/fir/fir_sync_fifo_tb.vhd
vfile add vhdl work src/DUT/units/EXECUTE.vhd
vfile add vhdl work src/DUT/units/CONTROL.vhd
vfile add vhdl work src/DUT/units/IFETCH.vhd
vfile add vhdl work src/DUT/units/WRITE_BACK.vhd
vfile add vhdl work src/DUT/units/HazardUnit.vhd
vfile add vhdl work src/DUT/units/IDECODE.vhd
vfile add vhdl work src/DUT/memory/DMEMORY.vhd
vfile add vhdl work src/DUT/utils/aux_package.vhd
vfile add vhdl work src/DUT/utils/memory_map.vhd
vfile add vhdl work src/DUT/utils/cond_comilation_package.vhd
vfile add vhdl work src/DUT/utils/const_package.vhd
vfile add vhdl work src/DUT/modules/nbit_shift_reg.vhd
vfile add vhdl work src/DUT/modules/nbit_timer.vhd
vfile add vhdl work src/DUT/modules/ALU.vhd
vfile add vhdl work src/DUT/modules/FIR/fir_base_unit.vhd
vfile add vhdl work src/DUT/modules/FIR/fir_reg_arr.vhd
vfile add vhdl work src/DUT/modules/FIR/fir_sync_fifo.vhd
vfile add vhdl work src/DUT/modules/FIR/fir_mod.vhd
vfile add vhdl work src/DUT/modules/nbit_latch.vhd
vfile add vhdl work src/DUT/modules/nbit_encoder.vhd
vfile add vhdl work src/DUT/modules/nbit_decoder.vhd
vfile add vhdl work src/DUT/modules/PLL.vhd
vfile add vhdl work src/DUT/modules/gpio/port_sw_interface.vhd
vfile add vhdl work src/DUT/modules/gpio/port_hex_interface.vhd
vfile add vhdl work src/DUT/modules/gpio/port_led_interface.vhd
vfile add vhdl work src/DUT/modules/nbit_dff.vhd
vfile add vhdl work src/DUT/modules/address_decoder.vhd
vfile add vhdl work src/DUT/modules/timer/timer_output_unit.vhd
vfile add vhdl work src/DUT/modules/timer/timer_core.vhd
vfile add vhdl work src/DUT/modules/timer/timer_unit.vhd
vfile add vhdl work src/DUT/modules/hex_driver.vhd
vfile add vhdl work src/DUT/core/MIPS.vhd
